### ISSUE TITLE
Very few options and no 'Custom' labels for each phone number/email address, etc

### ISSUE THREAD

**Issue by Reue** [SimpleMobileTools/Simple-Contacts#196] opened 2018-07-11 21:06 UTC
This applicantion has very few options for each phone number/email address, etc. It needs the extra options other apps have, like "Work mobile", "Callback", "Car", "Company main", "Radio", "Telex", "Work pager", "Assistant", etc.
And even more than that, this app needs a "Custom" label, like other applications have. I mean a "Custom" label where you can enter anything you want, like the name of a company, "Urgencies", "Work mobile", "Work email", etc.

**Comment by tibbi** [comment] 2018-07-11 21:09
duplicate of #149

**Closed by tibbi** 2018-07-11 21:09 UTC

**Comment by Reue** [comment] 2018-07-11 22:49
This is not a duplicate of #149. #149 only refers to the creation of "Custom" labels.
My bug report is not limited to the possibility of creating custom labels...
My bug report also refers to the problem of this application having very few options for each phone number/email address, etc. It needs the extra options other apps have, like "Work mobile", "Callback", "Car", "Company main", "Radio", "Telex", "Work pager", "Assistant", etc.
So please move this issue accordingly. It deserves to be autonomous by virtue of covering a new problem.
