### ISSUE TITLE
Q: Import to device storage (public) 

### ISSUE THREAD

**Issue by platinorum** [SimpleMobileTools/Simple-Contacts#773] opened 2022-01-24 17:10 UTC
Can I import to a source, stored on the device storage AND visible to other apps? I switched to Simple Contacts, because I didn't want to save my contacts in my google account, but I still want them to show up in WhatsApp, Signal, etc.

**Comment by platinorum** [comment] 2022-01-24 18:10
thx for the quick reply, I'm using app version 6.17.0 Pro and Android 11. When I'm trying to import my contacts via vcf, just "Phone storage (not visible by other apps)" and my google accounts show up. When I'm editing contact and click on the source, it's the same.

**Comment by tibbi** [comment] 2022-01-24 18:11
right, try creating a contact into casual Phone storage with some other app, then it should show up

**Comment by platinorum** [comment] 2022-01-24 18:26
cool thx, will it be possible to create a new source in the future?

**Comment by tibbi** [comment] 2022-01-24 22:39
well, I hope so, but I cannot reproduce the issue on any of my devices and it seems to be some weird device specific issue. Anyway, Ill close this as it should already be reported somewhere.

**Closed by tibbi** 2022-01-24 22:39 UTC

**Comment by platinorum** [comment] 2022-03-09 19:58
I added a source via an other app, but after a few weeks it gets deleted and only some contacts saved in WhatsApp and co remain saved.
