### ISSUE TITLE
UI for receiving calls

### ISSUE THREAD

**Issue by namandixit** [SimpleMobileTools/Simple-Contacts#345] opened 2019-01-06 01:02 UTC
Since this app now seems to be making use of the Telecom framework, it is showing up as an alternative to the "Phone" app by Google that comes preinstalled on most handsets. However, selecting this app as default app and disabling the Phone app results in being unable to receive incoming calls -- as even though the phone rings, there is no UI to receive the call.

Is this a bug or is this intended behaviour? If latter, will the corresponding functionality be implemented later on?

**Comment by tibbi** [comment] 2019-01-06 08:40
ye that is the intended for now, Im getting there step by step. Duplicate of #224

**Closed by tibbi** 2019-01-06 08:40 UTC
