### ISSUE TITLE
Unable to add contact from last called contacts in phone app

### ISSUE THREAD

**Issue by mobtechpd** [SimpleMobileTools/Simple-Contacts#139] opened 2018-04-15 22:15 UTC
I deleted default phone contacts app and now i cant open from phone last called to simple contacts, or if i wanna add number from last called it redirects to simple contacts but phone number field emty, i have to enter it manually

**Comment by tibbi** [comment] 2018-04-16 07:40
Can I somehow reproduce the issue? Is it a downloaded Phone app, or the stock one?

**Comment by mobtechpd** [comment] 2018-04-16 09:57
Stock one phone app, my system is cyanogenmod

**Comment by michaelof** [comment] 2018-05-24 09:26
I can confirm this bug on Android 6.0, simple-contacts v4.0.3 (F-Droid), WITHOUT having deleted the stock contacts app:

Steps to reproduce on my phone:

Having a reveived call in stock phone app, unknown contact , phone# only  :

a)
- click on round contact icon
- Android asks "Complete action using Contact" or "Use a different app" ("Details" from simple-contacts)
- click on "Details" for simple-contacts

RESULT: simple-contacts opens for a second and is closing immediately

b)
- click in ohone# instead
- submenu opens with "create new contact" / "add to a contact" / ..
- click on "create new contact"
- Click on "Complete action using Contacts (simple-contacts) "Just Once"
- simple-contacts opens in "New contact" mode

RESULT:  All fields are empty, phone# has not been pre-filled from list of calls

**Comment by genodeftest** [comment] 2018-09-13 09:07
I can confirm this issue too with the stock phone app and without having deleted the stock contacts app. I can reproduce both ways @michaelof is seeing.

My software versions:
Android 8.1.0, patchlevel 2018-08-01
Simple-contacts 4.4.0
(stock contacts app) 3.0.7.210756853
(stock phone app) 23.0.208561757

**Comment by tibbi** [comment] 2018-11-30 09:29
one similar case will be fixed in 6.1.0, reopen if it still isnt.

**Closed by tibbi** 2018-11-30 09:29 UTC
Labels: bug

**Comment by genodeftest** [comment] 2019-01-06 14:55
With simple-contatcs 6.1.2, I cannot reproduce any of the ways @michaelof has reported. Thank you very much!
