### ISSUE TITLE
Need a way to set custom ringtones per contact

### ISSUE THREAD

**Issue by alcoolfire** [SimpleMobileTools/Simple-Contacts#528] opened 2020-03-29 22:46 UTC
Unless I've missed something, Simple Contacts doesn't provide the means to set custom ringtones for individual contacts. Somehow I do have a custom ringtone for one contact, but have no idea how that got set (there's no reference to it in VCF backups) and I can't find anyplace to change it. I do not have Google Contacts installed on my phone. I'm requesting that this feature be added to Simple Contacts.

**Comment by tibbi** [comment] 2020-05-17 11:18
closing it as a duplicate of https://github.com/SimpleMobileTools/Simple-Dialer/issues/13 , all calling related functions will be moved into Simple Dialer soon

**Closed by tibbi** 2020-05-17 11:18 UTC
Labels: feature request

**Comment by alcoolfire** [comment] 2020-05-29 23:54
@tibbi: Please reconsider adding the setting of custom ringtones to the Simple Dialer app instead of Simple Contacts. For those of us **not** using Simple Dialer, we're left with no way to set such ringtones. The Google Phone dialer app, which I am using, does not provide the means to set custom ringtones, so you are not providing one-to-one replacement capability with this decision. Moreover, I would argue that Simple Contacts is all about managing contact metadata, which conceptually includes anything unique to the contact (eg. custom ringtone). Simple Dialer should merely be a consumer of metadata managed by Simple Contacts.

While I am at it, I would also like to see per-contact custom ringtones included in exported .VCF files from Simple Contacts, again because all per-contact metadata should be in one place managed by one tool/app.

We really like Simple Contacts and would not like to give it up merely because we want to stick with our built-in dialer app.
