### ISSUE TITLE
Scan qrcode to add contact

### ISSUE THREAD

**Issue by balporig** [SimpleMobileTools/Simple-Contacts#832] opened 2022-06-10 16:47 UTC
Add contact by scanning qrcode with vCard/meCard data encoded. When scanned, it should open a new contact's dialog with all available fields prefilled. Reference implementation: Samsung OEM contacts app
Reverse: #129

**Comment by tibbi** [comment] 2022-06-11 13:57
duplicate of #626

**Closed by tibbi** 2022-06-11 13:57 UTC
