### ISSUE TITLE
Import contact from automatic backup failed

### ISSUE THREAD

**Issue by Breizhux** [SimpleMobileTools/Simple-Contacts#1052] opened 2023-10-27 20:30 UTC
Hello,

**Following an error on my part, I wanted to re-import all my contacts from the .vcf file generated daily by the application... But the import fails, whatever the contact application.**
But it turns out that **it's absolutely not a vcf file inside**. It's a kind of **json file** that **doesn't follow any known standard**. The result is that I can't reimport my contacts, whatever the contact application.

_Or it's a file containing a backup of contacts and settings... In which case there would need to be a function for re-importing the application's backup. Or it's an export of all the contacts... In which case we would have to follow the standard already established, as is the case (in principle) with the manual export function._

This problem needs to be resolved as quickly as possible so that it doesn't happen to other people.
And if it were possible to add, at least temporarily, a function allowing this type of file to be imported, that would be great. Or else propose a small script to convert the fake vcf into a valid vcf.

At the moment, I have all my contacts saved in a file with the data I'd like to retrieve. But I don't have any way of using the file to retrieve the contents, other than to start programming to convert the json data into a usable vcard. And in any case, I lose the contact photos, because only a path is indicated in the file I've obtained.

Thanks in advance.

**Comment by Aga-C** [comment] 2023-10-28 06:07
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Contacts/issues/1043.

**Comment by Breizhux** [comment] 2023-10-28 10:17
Oopsss, sorry! But I'd looked to see if it hadn't already been opened...

**Closed** 2023-11-01 18:11 UTC
