### ISSUE TITLE
Entire address appears in Street attribute

### ISSUE THREAD

**Issue by Atalanttore** [SimpleMobileTools/Simple-Contacts#385] opened 2019-04-02 14:14 UTC
Hi

I've noticed that addresses added to contacts in Simple-Contacts appear completely in the **Street** attribute in other apps after synchronization via my CardDAV provider.

Regards,
Atalanttore

**Comment by tibbi** [comment] 2019-04-02 15:47
duplicate of #364

**Closed by tibbi** 2019-04-02 15:47 UTC
