### ISSUE TITLE
App quits while exporting contacts

### ISSUE THREAD

**Issue by akcansoft** [SimpleMobileTools/Simple-Contacts#618] opened 2020-10-24 14:22 UTC
app quits while exporting contacts to a .vcf file.
.vcf file is created, but all contacts are not in the file.

There are around 1000 people in the application.
Can a large number of people cause this problem?
It is not possible to query how many people are registered in the application.

Also it has no effect when selecting "settings / use english language".

my device: general mobile android one 4g
Android 7.1.1

app: Simple Contacts v6.13.0 Turkish

sorry my english. this text translated by google translate

**Comment by tibbi** [comment] 2020-10-24 17:39
not sure if size can be the issue, try selecting some contacts and doing Share, then sending yourself the file. That exports them the same way.

**Comment by akcansoft** [comment] 2020-10-25 07:32
I did it as you specified. There was no problem.
However, while "exporting contacts to vcf file", the application quits.

Message after closing:
```
Contacts stopped
- Open the app again
- Send feedback
```

**Comment by tibbi** [comment] 2020-10-25 08:23
even if you share just a few contacts, or not? Can you maybe check if it isnt one specific contact breaking it?

**Comment by akcansoft** [comment] 2020-10-26 14:35
![a1](https://user-images.githubusercontent.com/7031346/97185798-8dc3c600-17b1-11eb-9681-0b39cc95bda8.gif)

**Comment by tibbi** [comment] 2020-10-27 17:05
Try selecting just a couple contacts by long pressing, then using Share at the top menu. Does it work?

**Comment by akcansoft** [comment] 2020-10-27 17:34
Yes. it worked. There is no problem with this method.
But
Contact list is not selected / Menu / Export contacts to a vcf file
application quits.

Message after closing:
Contacts stopped
- Open the app again
- Send feedback

**Comment by tibbi** [comment] 2020-10-27 18:56
They use the same mechanism. So if you long press one contact, then click on the number in the top left corner to select all contacts and do Share, does it crash the same way? If it does, try pinponting please which contact is crashing it. You can select multiple contacts by long pressing one, then long pressing another and everything in between gets selected.

**Comment by akcansoft** [comment] 2020-10-27 19:16
I know how to select one or more contacts or all contacts. Select contact(s) and Using Share, no problem.
There are 1294 contacts on the list.
It is very difficult to determine which contact is causing problems.

**Comment by tibbi** [comment] 2023-06-23 16:07
duplicate of #681

**Closed by tibbi** 2023-06-23 16:07 UTC
