### ISSUE TITLE
Edit button lead's to e.g. signal contact

### ISSUE THREAD

**Issue by stoneubi** [SimpleMobileTools/Simple-Contacts#788] opened 2022-02-13 22:01 UTC
Hi there,

My setup: own addressbook and signal

Once the edit button is selected the signal contact edit screen is displayed. This is misleading as normally the contact of the address book will be edited. 

![Screenshot_2022-02-13-22-54-25-10_ed5b588ea0ef6c9a299100fc3989c22d_1](https://user-images.githubusercontent.com/32926093/153777043-a5e504d2-059f-4cf7-83fe-bfc0fc901da3.jpg)

![Screenshot_2022-02-13-22-54-32-84_ed5b588ea0ef6c9a299100fc3989c22d_1](https://user-images.githubusercontent.com/32926093/153777047-c24ef859-5457-4203-82dc-3fa62d57b464.jpg)

Thank you
Stoneubi

**Comment by tibbi** [comment] 2022-02-13 22:05
duplicate of #598

**Closed by tibbi** 2022-02-13 22:05 UTC
