### ISSUE TITLE
Some Contacts suddenly mute

### ISSUE THREAD

**Issue by Jumbo125** [SimpleMobileTools/Simple-Contacts#814] opened 2022-04-26 08:06 UTC
Hello 
I don't know if i do something wrong, but i have sometimes the same problem.

When i get an incomming call, i don't hear any ringtone.
The ringtone sound is on.

So i go into Contacts, search the "problem-Contact" and watch the details.
There is a liine, which show the ringtone name. Suddenly there is "stumm (mute in German)"... I can edit the contact and select the ringtone again. 
I've had this situation more than three times (different contacts).

Does anybody know, why the contact suddenly mute/lose the ringtone

Thank you

**Comment by tibbi** [comment] 2022-04-26 08:08
dont you have it somewhere set as the default in your device settings?

**Comment by Jumbo125** [comment] 2022-04-26 08:18
i had set it in my default. It choosed it since i have the phone

**Comment by Jumbo125** [comment] 2022-04-26 12:20
mayby it's my mistake. 
By the way another little question. 
I hav more than 50 missed calls. I always call back, but the counter doesn't reset to zero. is there any easy solution? thank you

**Comment by tibbi** [comment] 2022-04-26 12:35
not sure what is causing that. Anyway, it is handled by Simple Dialer app, so duplicate of https://github.com/SimpleMobileTools/Simple-Dialer/issues/256

**Closed by tibbi** 2022-04-26 12:35 UTC
