### ISSUE TITLE
Cannot return to call in progress after using device's back button

### ISSUE THREAD

**Issue by judge2b** [SimpleMobileTools/Simple-Contacts#567] opened 2020-05-19 15:47 UTC
After initiating a phone call from the Contacts app, if you tap the mobile device's back button enough times, the call-in-progress screen disappears and there is no way to return to the call in progress from within the application. Going to the dialer again in the app presents the dialer as if no call is in progress and it appears as if you can make a new call now.

Environment:
Motorola G7 Power (XT1955-5)
Android version 9

**Comment by smilearric** [comment] 2020-05-20 11:54
Same on Oneplus 5T Android 9

**Comment by tibbi** [comment] 2020-05-25 10:14
all calling related functionality has been moved into Simple Dialer, it will be solved by having a persistant notification. Duplicate of https://github.com/SimpleMobileTools/Simple-Dialer/issues/23

**Closed by tibbi** 2020-05-25 10:14 UTC
Labels: feature request
