### ISSUE TITLE
"Phonetic Name" field

### ISSUE THREAD

**Issue by dkavlakov** [SimpleMobileTools/Simple-Contacts#242] opened 2018-08-27 00:34 UTC
This field is quite crucial for those who use non-Latin charrset. Without it (and due to the lack of instant messaging fields) the program is practically usable only as a way to add birthday/etc info to contacts, created by the stock contacts app.

**Comment by tibbi** [comment] 2018-08-27 06:26
duplicate of #133

**Closed by tibbi** 2018-08-27 06:26 UTC
