### ISSUE TITLE
java.lang.IllegalArgumentException:Invalid format / vcf / bday

### ISSUE THREAD

**Issue by Machion** [SimpleMobileTools/Simple-Contacts#255] opened 2018-09-19 21:50 UTC
Hi, 

I found out, the app maybe has problems importing vcard/vcf-files when there is a BDAY-line in it. 
Initially I tried to import a vcard2.1 file and it came the discrete error on the screen mentioned in the title. 
For testing purpose I created a new contact (with a birthday entry) with the app and exported it. It was a vcard3.0 file and after trying to reimport it, there was the same error.

**Comment by tibbi** [comment] 2018-09-19 22:01
what app version do you have?

**Comment by Machion** [comment] 2018-09-20 07:49
Sorry, in the morning I realized I forgot something :) 
I'm using 4.4.0 
When I delete the line with BDAY or create an account without bday-information, than import just works fine.

**Comment by tibbi** [comment] 2018-09-20 08:26
paste me the BDAY line here please, hope I can reproduce the issue.

**Comment by Machion** [comment] 2018-09-20 08:52
BDAY:2018-07-20 
or 
BDAY:20180720
It doesn't matter. 

Btw I use Android 8.0.0 

Another strange thing I just realized: 
I installed signal and now in your app I can only see contacts, which are also in signal. Non-signal accounts are gone. I don't know, if there were deleted or just hidden. Is this a signal problem/wrong setting?

**Comment by tibbi** [comment] 2018-09-20 09:33
try pressing the "Filter" menu button, maybe some sources just got untoggled.

**Comment by tibbi** [comment] 2018-09-20 09:44
try disabling "Try filtering duplicate contacts" in Simple Contacts, or uninstall Signal, to see if anything changes. Anyway don't spam this thread, either create a new one or shoot me an email at hello@simplemobiletools.com if it still wont work. Thanks

**Comment by tibbi** [comment] 2018-09-27 09:01
it works fine to me, please paste me the whole contact from the .vcf file, starting with BEGIN:VCARD, ending with END:VCARD. Feel free censoring out the name, number, address etc.

**Comment by Machion** [comment] 2018-09-28 09:38
BEGIN:VCARD
VERSION:2.1
N:Bud;Test;;;
FN:Test Bud
TEL;CELL: +43 650 1234567
BDAY:2018-08-12
END:VCARD

BEGIN:VCARD
VERSION:3.0
PRODID:ez-vcard 0.10.4
N:Bud;Test
TEL;TYPE=CELL:+43 650 1234567
BDAY:2018-08-12
END:VCARD

What's additionally very strange: When I have Signal installed (with issue #257) import works surprisingly (the import dialog box says "Target contact source - Signal"). Then I uninstalled Signal and tried to import above contact again. Dialog box still says "Target contact source - Signal" now followed by error message: 

java.lang.IllegalArgumentException: Must specify both or neither of ACCOUNT_NAME and ACCOUNT_TYPE; URI: content://com.android.contacts/raw_contacts, calling user:com.simplemobiletools.contacts, calling package:com.simplemobiletools.contacts 

The issue started with no connection to signal, because I installed simplecontacts on a fresh android before signal, but now Signal puts a new layer of error on top of it?

I don't know much about android programming, but are there any system services the contact database relies on? I tried to deactivate as many google apps/services I could, without rooting the device. So for example I deactivated the google contacts app to replace it 100% with your app. The phone call app is the only google app left on the device I have to use.

**Comment by tibbi** [comment] 2018-09-28 09:44
apparently Signal and Telegram can cause some weird issues, but there are still some unknown things to be related to storing contacts so I havent been able to solve them yet. Hope I will be able to fix it soon. Thanks

**Comment by tibbi** [comment] 2018-09-28 12:41
from version 4.5.0 you wont be able to add contacts into Signal and Telegram via Simple Contacts, apparently it is not the desired behaviour and it doesnt work that way.

**Comment by Machion** [comment] 2018-10-04 21:11
I will test it as soon as the new version is available on fdroid. 
I never tried to import contacts into signal with the "system contacts app", so this possibility surprises me. And yes signal should only scan the main contacts (database) and compare the phone numbers with contacts which have signal installed and make it's own list. 
Thanks for the work around. 

Am 28. September 2018 14:41:32 MESZ schrieb Tibor Kaputa <notifications@github.com>:
>from version 4.5.0 you wont be able to add contacts into Signal and
>Telegram via Simple Contacts, apparently it is not the desired
>behaviour and it doesnt work that way.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SimpleMobileTools/Simple-Contacts/issues/255#issuecomment-425423048

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Machion** [comment] 2018-10-11 13:55
So I tested V4.5.0... but nothing changed. At least for me. 
Can't import contacts with bday. And with Signal installed, I can only see signal contacts. 

For comparison reason I reactivated the built in Google Contacts app (v1.7.10) and there are no such problems. Strange.

**Comment by aGrimRepoMan** [comment] 2018-11-11 21:31
Just as an additional information point:
  Using v6.0.0 version of Simple Contacts Pro, I am also unable to import contacts that have a "BDAY:" line.

  The vcf contact file I'm trying to import is generated by an export from the Thunderbird email client's "CardBook" add-on (https://gitlab.com/CardBook).  I tried both a VCF v3.0 and a VCF v4.0 contact file.

After importing, I don't see an "illegal argument" message, just a message something to the effect of "Not all contacts imported" (sorry, I didn't write down the exact message).  Indeed, the first few contacts in the file do not have a "BDAY:" line, and are successfully imported.  But then the next contact, one which has the "BDAY:" line, is not imported, and all subsequent contacts (with or without the "BDAY:" line) are also not imported.

**Comment by tibbi** [comment] 2018-11-11 21:39
can you paste me a sample BDAY line that doesnt work? Thanks

**Comment by aGrimRepoMan** [comment] 2018-11-12 14:47
Sure.... Below is an (anomymized) contact exported from version 32.8 of the "Cardbook" Thunderbook add-on.  When imported into Simple Contacts Pro v6.0.0, it fails with message: "Importing failed".  If I remove the "BDAY:" line, it imports successfully.

BEGIN:VCARD
VERSION:4.0
PRODID:-//Thunderbird.net/NONSGML Thunderbird CardBook V30.5//EN
UID:9108ebf0-f440-41a8-b661-f61fd9e6dcff
CATEGORIES:Abcdef's Family
FN:Bill Xyzabc
N:Xyzabc;William;;;
NICKNAME:Bill
BDAY:19731221
GENDER:M
REV:20181111T135821Z
EMAIL;PREF;TYPE=HOME:billxyzabc@efgh.ijk.lmn
EMAIL;TYPE=HOME:abcd@x-pqrst.com
TEL;TYPE=HOME:+852 9999 8888
TEL;TYPE=FAX:+852 7777 6666






ADR;TYPE=HOME:;Flat 2A\, Block 8;5 Aa Bbbb St.;Abcd Def;;;Abcd Efgh
NOTE:aa's xxxxxxx-xx-xxx\nXxxxxxx: January 1999?\nVoIP: 1111-2222
END:VCARD

**Comment by aGrimRepoMan** [comment] 2018-11-12 15:04
Sure....  Below are the contents of 4 files which are (anomymized) contacts exported from version 32.8 of the "Cardbook" Thunderbook add-on.  (Sorry, have to paste them as text, since github gives me an error when I try to attach a Zip file).

When imported into Simple Contacts Pro v6.0.0, the following two files, both of which have "BDAY:" lines, fail with message: "Importing failed":
  - Bill Xyzabc (VCF v3.0).vcf
  - Bill Xyzabc (VCF v4.0).vcf

Whereas the following two files, which don't have the "BDAY:" line, import successfully:
 - Bill Xyzabc (VCF v3.0) No BDAY.vcf
 - Bill Xyzabc (VCF v4.0) No BDAY.vcf

%% File 1, "Bill Xyzabc (VCF v3.0).vcf":
BEGIN:VCARD
VERSION:3.0
PRODID:-//Thunderbird.net/NONSGML Thunderbird CardBook V30.5//EN
UID:9108ebf0-f440-41a8-b661-f61fd9e6dcff
CATEGORIES:Yyyyyy's Family
FN:Bill Xyzabc
N:Xyzabc;William;;;
NICKNAME:Bill
BDAY:1973-12-21
REV:2018-11-12T09:37:11Z
EMAIL;TYPE=PREF;TYPE=HOME:billxyzabc@efgh.ijk.lmn
EMAIL;TYPE=HOME:abcd@x-pqrst.com
TEL;TYPE=HOME:+333 9999 8888
TEL;TYPE=FAX:+333 7777 6666
ADR;TYPE=HOME:;Flat 2A\, Block 8;5 Aa Bbbb St.;Abcd Def;;;Abcd Efgh
NOTE:aa's xxxxxxx-xx-xxx\nXxxxxxx: Xxxxxxx 1111?\nVoIP: 1111-2222
X-GENDER:M
END:VCARD

%% File 2, "Bill Xyzabc (VCF v4.0).vcf":
BEGIN:VCARD
VERSION:4.0
PRODID:-//Thunderbird.net/NONSGML Thunderbird CardBook V30.5//EN
UID:9108ebf0-f440-41a8-b661-f61fd9e6dcff
CATEGORIES:Yyyyyy's Family
FN:Bill Xyzabc
N:Xyzabc;William;;;
NICKNAME:Bill
BDAY:19731220
GENDER:M
REV:20181112T093720Z
EMAIL;PREF;TYPE=HOME:billxyzabc@efgh.ijk.lmn
EMAIL;TYPE=HOME:abcd@x-pqrst.com
TEL;TYPE=HOME:+333 9999 8888
TEL;TYPE=FAX:+333 7777 6666
ADR;TYPE=HOME:;Flat 2A\, Block 8;5 Aa Bbbb St.;Abcd Def;;;Abcd Efgh
NOTE:aa's xxxxxxx-xx-xxx\nXxxxxxx: Xxxxxxx 1111?\nVoIP: 1111-2222
END:VCARD

%% File 3, "Bill Xyzabc (VCF v3.0) No BDAY.vcf":
BEGIN:VCARD
VERSION:3.0
PRODID:-//Thunderbird.net/NONSGML Thunderbird CardBook V30.5//EN
UID:9108ebf0-f440-41a8-b661-f61fd9e6dcff
CATEGORIES:Yyyyyy's Family
FN:Bill Xyzabc
N:Xyzabc;William;;;
NICKNAME:Bill
REV:2018-11-12T09:37:11Z
EMAIL;TYPE=PREF;TYPE=HOME:billxyzabc@efgh.ijk.lmn
EMAIL;TYPE=HOME:abcd@x-pqrst.com
TEL;TYPE=HOME:+333 9999 8888
TEL;TYPE=FAX:+333 7777 6666
ADR;TYPE=HOME:;Flat 2A\, Block 8;5 Aa Bbbb St.;Abcd Def;;;Abcd Efgh
NOTE:aa's xxxxxxx-xx-xxx\nXxxxxxx: Xxxxxxx 1111?\nVoIP: 1111-2222
X-GENDER:M
END:VCARD

%% File 4, "Bill Xyzabc (VCF v4.0) No BDAY.vcf":
BEGIN:VCARD
VERSION:4.0
PRODID:-//Thunderbird.net/NONSGML Thunderbird CardBook V30.5//EN
UID:9108ebf0-f440-41a8-b661-f61fd9e6dcff
CATEGORIES:Yyyyyy's Family
FN:Bill Xyzabc
N:Xyzabc;William;;;
NICKNAME:Bill
GENDER:M
REV:20181112T093720Z
EMAIL;PREF;TYPE=HOME:billxyzabc@efgh.ijk.lmn
EMAIL;TYPE=HOME:abcd@x-pqrst.com
TEL;TYPE=HOME:+333 9999 8888
TEL;TYPE=FAX:+333 7777 6666
ADR;TYPE=HOME:;Flat 2A\, Block 8;5 Aa Bbbb St.;Abcd Def;;;Abcd Efgh
NOTE:aa's xxxxxxx-xx-xxx\nXxxxxxx: Xxxxxxx 1111?\nVoIP: 1111-2222
END:VCARD

**Comment by tibbi** [comment] 2018-11-29 21:52
a related glitch will be fixed in 6.1.0 released soon, reopen if it is still broken please

**Closed by tibbi** 2018-11-29 21:52 UTC
Labels: bug
