### ISSUE TITLE
Encrypted contacts option

### ISSUE THREAD

**Issue by meximan** [SimpleMobileTools/Simple-Contacts#603] opened 2020-08-29 11:21 UTC
In this day and age, privacy is everything.

I feel it's an "issue" that Simple contacts doesn't have the option to encrypt the contacts or add a password to view contacts.

I feel this would greatly enhance its customer base.

Thank you! (I'm using all your apps).

**Comment by tibbi** [comment] 2020-08-31 07:02
duplicate of #602

**Closed by tibbi** 2020-08-31 07:02 UTC
