### ISSUE TITLE
Option to delete duplicate contacts 

### ISSUE THREAD

**Issue by nulledone** [SimpleMobileTools/Simple-Contacts#84] opened 2018-03-04 00:25 UTC
My contacts seems to be doubled unexpectedly can you add an option to remove dupes?

**Comment by tibbi** [comment] 2018-03-04 07:59
ye contacts on android are messed up, I have duplicates in some apps too. Anyway this is ironically a duplicate of #53

**Closed by tibbi** 2018-03-04 07:59 UTC
