### ISSUE TITLE
[Feature request] sync contacts to the plain file

### ISSUE THREAD

**Issue by FlrQue** [SimpleMobileTools/Simple-Contacts#774] opened 2022-02-03 10:33 UTC
I suggest adding option to sync all contacts to the plain file like *.vcf

It would be cool as I dont want to sync them with Google, I would love to have periodically created file with all my contacts so I can make automated rsync job or something

**Comment by tibbi** [comment] 2022-02-03 11:28
duplicate of #361

**Closed by tibbi** 2022-02-03 11:28 UTC
