### ISSUE TITLE
Feature Request: Auto-backup contacts to file

### ISSUE THREAD

**Issue by mooreye** [SimpleMobileTools/Simple-Contacts#863] opened 2022-08-08 16:26 UTC
I would love to see a feature where when any changes are made to any contact, a `.vcf` file is automatically exported to some dir on your phone, just like Signal's backups create themselves periodically to a file. This way I wouldn't have to remember to export contacts every time I make a change (which are not in any cloud) and not have to go through the hassle of setting up CardDAV but just leverage Syncthing instead which many people already use.

**Comment by tibbi** [comment] 2022-08-08 17:17
duplicate of #361

**Closed by tibbi** 2022-08-08 17:17 UTC
