### ISSUE TITLE
cannot remove searchbar filter after tab switch

### ISSUE THREAD

**Issue by k3b** [SimpleMobileTools/Simple-Contacts#200] opened 2018-07-12 06:41 UTC
There is no way to get rid of the last searchbar expression after tab switch

I am using latest version 4.05 from fdroid on non rooted android 7.1 phone

how to reproduce:

* press the searchbar  button ==> searchbar appears
* enter "pet" ==> only contacts that contain "peter" are visible
* goto group tab (right tab)
* go back to contact tab (left tab) => searchbar is closed only "peter" entries are visible i.e. filter is still on "pet"
* press the searchbar  button ==> empty searchbar appears

there is currently no way to remove the searchbar without exiting the app* go to contact tab (left tab)

i would expect that when returning to contact tab (left tab) that the searchbar is still open with the current active search expression

**Comment by tibbi** [comment] 2018-07-16 21:49
the intended behaviour for now is closing the search when the tab changes and not resuming it if the user goes back. The built in Android Search itself is a pretty cumbersome and buggy element, I dont really want to mess with it.

**Closed** 2018-07-16 21:48 UTC
Labels: bug
