### ISSUE TITLE
[bug] Saving contact impossible when keyboard is in use

### ISSUE THREAD

**Issue by Aircan** [SimpleMobileTools/Simple-Contacts#946] opened 2023-02-21 22:06 UTC
When creating a new or editing an existing contact saving (via hook on top of the screen) is not possible with the keyboard in use (e.g. when enterning an address) because scrolling to top does not work. You have to minimize keyboard to be able to access the save button (hook).

**Comment by Aga-C** [comment] 2023-02-22 07:33
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Contacts/issues/866.

**Comment by Aircan** [comment] 2023-02-22 11:22
Hence, can be closed. Thanks.

**Closed** 2023-02-22 11:50 UTC
