### ISSUE TITLE
Support "default number" for action

### ISSUE THREAD

**Issue by AeliusSaionji** [SimpleMobileTools/Simple-Contacts#159] opened 2018-05-03 13:20 UTC
As shown, the contacts app in Oreo allows me to select a number to always be default for the Call, SMS, and Email buttons. I believe this is a setting that reaches system-wide, because the KISS launcher definitely makes use of it.

Simple Contacts does not respect the default preference set by the system, nor does it have the ability to set it.

![](https://i.imgur.com/3mcHX7Z.jpg)

**Comment by HoWilgh** [comment] 2019-04-30 09:52
+1 this means you always have to click twice in the contacts-details of this contacts app (phone-symbol and than number) which is a bit annoying.

**Comment by alcoolfire** [comment] 2019-07-09 08:05
What is the current algorithm in Simple Contacts for selecting which phone number, texting number, or email address will be used?

**Comment by tibbi** [comment] 2020-05-17 11:20
closing this as a duplicate of https://github.com/SimpleMobileTools/Simple-Dialer/issues/15 , all calling related functions will be moved into Simple Dialer soon

**Closed by tibbi** 2020-05-17 11:20 UTC
Labels: feature request

**Comment by alcoolfire** [comment] 2020-05-30 00:06
As per my comment in #528, I see the tagging of one of a contact's number as default as a piece of per-contact metadata. The job of Simple Contacts ought to be to manage all per-contact metadata, including custom ringtones and default numbers. Simple Dialer should merely be a consumer of the metadata managed by Simple Contacts. When I go into Simple Contacts to export the metadata it manages to a VCF file, I naturally expect that file to include all such metadata.

As far as I know, Google's own built-in dialer app does not provide the means to specify a default number for a contact (nor custom ringtones), so Simple Dialer is not going to be a one-to-one replacement. For those of us who want (or need) to use our built-in dialer but love Simple Contacts, what are we to do?
