### ISSUE TITLE
Bug With Changing Ringtone

### ISSUE THREAD

**Issue by GithubContributor832** [SimpleMobileTools/Simple-Contacts#748] opened 2021-12-11 11:16 UTC
Changing the ringtone is fine until you hit the default ringtone at top or none. "Default ringtone" don't add the default in line next to the actual ringtone like it starts with a new contact but does change to correct ringtone. Then "none" doesn't work at all.

https://user-images.githubusercontent.com/92182796/145674488-c8ccfbb5-4cce-4ec1-a3a7-9ab5093814e5.mp4

**Comment by GithubContributor832** [comment] 2021-12-11 11:18
Thanks for adding tab storing on change event instead of destroy by the way.

**Comment by tibbi** [comment] 2021-12-11 13:30
duplicate of #684

**Closed by tibbi** 2021-12-11 13:30 UTC
