### ISSUE TITLE
Please support the multi-field VCARD 'ADR' property

### ISSUE THREAD

**Issue by sciurius** [SimpleMobileTools/Simple-Contacts#696] opened 2021-07-22 19:44 UTC
VCARD oriented data servers have a 7-field address property, ADR (see https://datatracker.ietf.org/doc/html/rfc6350#section-6.3.1). This allows for separate maintenance of e.g. street, city, zipcodes. According to my information Android also supports this.

Simple-Contacts, just like many other Contacts apps, supports a single, optionally multi-line, address field. While this is okay for many purposes, problems arise when the data is exchanged with VCARD oriented data servers. The individual field contents gets lost, and is replaced by a single address field. Other tools that use the VCARDs get confused since the data no longer conforms to the VCARD specification.

For display and maintenance of names (N property, which has a similar behaviour), Simple-Contacts allows the user to choose which fields (firstname, surname, ...) are shown and maintains the underlying fields.

My request is to provide a similar facility for ADR properties.

**Comment by tibbi** [comment] 2021-07-22 21:33
duplicate of #364

**Closed by tibbi** 2021-07-22 21:33 UTC

**Comment by sciurius** [comment] 2021-07-23 06:00
#364 is a feature request that, indeed, dups this issue. 
#385 is a bug. It feels a bit weird to close a bug with a feature request.
