### ISSUE TITLE
How to allow other apps to see contacts

### ISSUE THREAD

**Issue by elesto** [SimpleMobileTools/Simple-Contacts#801] opened 2022-03-31 17:39 UTC
I have my contacts in the app but the only option is phone storage which is not visible by other apps, notably whatsapp. How do i allow whatsapp to see my contacts so I get names instead of phone numbers

**Comment by tibbi** [comment] 2022-03-31 19:48
what app and OS version are you using?

**Comment by elesto** [comment] 2022-04-01 02:13
6.18.0 from fdroid and im running android 12 on a sony xperia 5 II

**Comment by elesto** [comment] 2022-04-01 22:15
Yes google contacts had the ability to call on whatsapp. Other than that I dont know of any other contacts apps. Id like to move away from google apps so a fix would be appreciated if possible

**Comment by tibbi** [comment] 2022-04-02 06:40
WhatsApp is unrelated. I mean if you are allowed to store contacts into any other place with some other app, because I dont think this issue is caused by our app.

**Comment by elesto** [comment] 2022-04-02 16:08
Im a bit confused. Do you know of any app that I could use to test your claims? Your app only allows "phone storage" when creating a contact with it. Should there be other options? Because as phone storage the label claims "other apps cannot view your contacts"

**Comment by tibbi** [comment] 2022-04-02 16:11
well, just search for some popular Contacts app on Google Play

**Comment by elesto** [comment] 2022-04-04 18:26
![Screenshot_20220404-141149](https://user-images.githubusercontent.com/24771215/161607341-2bfc7bee-b1b6-4929-aaf8-c4ee73d2862c.png)
Hi, forgive me because im not familiar with how contacts are stored and used on android. Currently I am only able to save to phone storage which does not allow other apps to see who is calling or messaging ect ect.. Is this a me problem or your app?

**Comment by tibbi** [comment] 2022-04-04 18:48
not sure, thats what Im telling you. Try using some other Contacts app if you have other contact sources visible there.

**Comment by elesto** [comment] 2022-04-08 16:33
I have tried a couple other contacts apps like you asked (google contacts, sony contacts) and they both store the contacts in a place where they can be read by other apps. But now after uninstalling them and trying your app again I now have three options that must have been left behind by these other apps. DEVICE, Phone Contacts, and Phone Storage (not visible by other apps). I am left with quite a mess now. All I want is your app with the ability for other apps to view my contacts.

**Comment by tibbi** [comment] 2022-04-08 17:08
try creating 1 contact with one of those other apps to an accessible place, then it should show up in Simple Contacts too

**Comment by elesto** [comment] 2022-04-08 17:27
Yes thanks, that works. Will you add the functionality to create these accessible places in your app? Maybe allow removing them also since I now have excess because of all the contacts apps I have tried.

**Comment by tibbi** [comment] 2022-04-08 18:03
well, thats what Im trying to do, but it still seems to glitch on some devices. Improving it is on the roadmap, but Ill close this issue as it is reported already.

**Closed by tibbi** 2022-04-08 18:03 UTC

**Comment by girlmaya** [comment] 2023-02-19 21:17
> Ill close this issue as it is reported already.

Hi, where is the main issue ? On f-droid 6.22.1 still cant see SMT contacts in whatsapp. Cant use any contacts with whatsapp at all actually because "Add contact" opens in SMT contacts.
