### ISSUE TITLE
When opening app, it takes too long (more than 5secs) to show the contacts

### ISSUE THREAD

**Issue by joeyLaus** [SimpleMobileTools/Simple-Contacts#381] opened 2019-03-29 06:46 UTC
As described in the title, on Android 9.0 the Contacts app takes too long for list of contacts to appear.  I dont know why this is happening.

Contacts were imported from a vcf card. and even when having imported them, took too long to appear.

This is really a great app to replace the stock Contacts app in LineageOS however if it takes too long to display the contacts it becomes unusable. Until this is fixed i won't be able to fully replace the stock app.

**Comment by tibbi** [comment] 2019-03-29 07:48
duplicate of #201

**Closed by tibbi** 2019-03-29 07:48 UTC
