### ISSUE TITLE
Issue importing/exporting contacts

### ISSUE THREAD

**Issue by StenSipma** [SimpleMobileTools/Simple-Contacts#377] opened 2019-03-09 14:13 UTC
* App Version: v6.3.1 (F-Droid)
* Android: 8.0.0

There seems to be some kind of problem in exporting an entire contact book (if that is the correct term for it). Here is how it is likely possible to reproduce:
____________
1. Create a contact somewhere, and exported it to vCard 3.0 (.vcf), which produced the following file:
> BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.6//EN
UID:500e384d-4387-45a3-8732-529ea518c969
FN:Test Contact
EMAIL;TYPE=HOME:testl.email@contacts.com
TEL;TYPE=CELL:0651424170
CATEGORIES:NewGroup,Test Group
N:Contact;Test;;;
BDAY:20190227T144137
END:VCARD
2. Import the contact with the simple contacts app, by clicking the top-right options button and selecting 'Import contacts from a .vcf file'.
3. The contact appears correctly, including added groups etc. so far so good!
4. Now export the contact from the same top-right menu selecting 'Export contacts to a .vcf file'.
5. Select a folder + press OK.
6. Select the contact source which has the contact we just imported.
7. Export.
8. Open the file with any text editor, which produces (only a fragment shown):
> ...
BEGIN:VCARD
VERSION:3.0
PRODID:ez-vcard 0.10.5
N:Contact;Test
END:VCARD
...

This final exported file shows only contacts in this format, so it does not include any additional information which should be in there (phone numbers, dates, etc.).
___________

On an additional note, if I select the note by holding it down, clicking share and share it with Nextcloud (which produces a .vcf file), it produces the following file:
> BEGIN:VCARD
VERSION:3.0
PRODID:ez-vcard 0.10.5
N:Contact;Test
TEL;TYPE=CELL:0651424170
EMAIL;TYPE=HOME:testl.email@contacts.com
BDAY:2019-02-27
END:VCARD

Which does show all the correct information, except for the groups (but this might be intended behavior).

If there is any additional information I can provide, please ask!

**Comment by matsimon** [comment] 2019-03-10 11:56
Hi

Thanks Tibor for your work on this app! Seems I've run much into the same problem as Sten on an Moto G5 Plus (Android 8.1.0, patch level December 2018) since I wanted to migrate to the new version from F-Droid as the contacts shown in 5.1.9 from the contact store were not shown in 6.3.1.

I've gone back with versions from F-Droid made these findings (maybe Sten could compare and see if my findings corelate?):
* 6.2.0, 6.3.0, 6.3.1: 
 * Says it imports the VCF, but doesn't actually import anything
 * These versions don't show the contact store from 5.1.9
* 6.1.2 from F-Droid archive: 
 * Shows the contact storage from 5.1.9
 * Can import a single-contact VCF file

This would indicate that there has been a regression at some point between 6.1.2 and 6.2.0.

I should add that the following differences
* 5.1.9 during the export process shows the option to select "Contact store" and "Contact store  (not visible for other apps" 
* 6.2-6.3.1 during import only showed "Contact store (not visible...)" during import.
* 6.1.2 during import showed second checkbox like 5.1.9, however the text is missing

As Sten wrote, if I can provide you with additional or debug data, please ask away, I'm happy if there is anything to help you in helping us :-)

-- Mathieu

**Comment by tibbi** [comment] 2019-03-10 15:03
which account source were you importing the contacts to? I mean the last field at checking out a contact. Is it some google email, or the "Phone storage (not visible by other apps)"? Thanks

**Comment by matsimon** [comment] 2019-03-10 16:26
Hi Tibor

Thanks for you reply, in my case this device uses the local Contact Storage synced to a Computer using MyPhoneExplorer. The device doesn't even use a google contacts at all, I don't think that Lenovo provide some sort of its own accounts (like Samsung does).

However I was able to compare against a older LG Nexus 5 (Android 7.1.2/LineageOS 14.1) where importing a contact into both Google contacts and a local account work for what I can tell. The function doesn't seem to be "broken" per se since then.

Although I'm not an Android developer I've tried to look at the commits between 6.1.2 and 6.2.0, most were pretty small changes or translation improvements, those 3 commits however do change code or update dependencies:
* 0a150a9f82e60084ce6a8b4497781bcb9662b454: updating commons and ezvcard -> Maybe a regression there?
* 4dcb46c7abe8e991bc3ad8bcd670bbb1302be6d0: remove notion of local account and type -> I don't know what that would mean exactly.
* 50dc97e9c0180765522aa8e40f723280d1df6f90: minor code cleanup here and there -> Bumped some dependencies.

I don't have a Android development environment at hand to build versions from git that would precede these changes to pin things down more closely for you. (yet)

**Comment by tibbi** [comment] 2019-03-10 16:30
it was the "remove notion of local account and type" commit that broke it, while it fixed the app to some users. The problem is that all those solutions avoiding google and syncing are done so differently, that it is hard to handle them all properly. As soon as I manage reproducing the issues I will be able to fix them, but for now I wasnt able to do it.

**Comment by StenSipma** [comment] 2019-03-10 16:52
I am not sure what location I used for the example, but I think I used a location called PHONE, (there is another one which is 'Phone storage (these will not be seen by other apps)'). I thought this was the default location for my contacts, as it is where most of my contacts were.

I also use the DavX5 app (previously DAVdroid) to sync contacts with NextCloud. This sync app is supported by the Simple Calender app.
Exporting from this location seems to have the same behaviour as I described above.

I won't be able to experiment more at the moment, maybe I have time later this week.

**Comment by mcladyz** [comment] 2019-06-13 15:18
I'm also experiencing this. Not exporting phone numbers is a critical bug!

**Comment by tibbi** [comment] 2019-06-14 19:15
what app version do you have? I cannot reproduce it with 6.3.1

**Comment by mcladyz** [comment] 2019-06-14 19:26
Same version and just re-tested it and still fails.

**Comment by tibbi** [comment] 2019-06-14 19:47
if you select a contact by long pressing, press Share, send yourself the file for example via an email, then open the .vcf file with a text editor, does it contain a line starting with "TEL"? That should contain the phone number.

**Comment by mcladyz** [comment] 2019-06-14 19:50
I does not export the number even on single contact export.

**Comment by tibbi** [comment] 2019-06-14 19:53
weird... do you have the contact stored under "Phone storage (not visible by other apps)", or under some casual email? If you try creating a new contact with just a name and a number under any contact source, does exporting work well?

**Comment by mcladyz** [comment] 2019-06-14 19:59
It doesn't work even when I create a contact and try to export it. My account is DecSync Contacts.

**Comment by tibbi** [comment] 2019-06-14 20:02
maybe it is caused by some setting, can you send me a screenshot of your settings screen? The part with all check buttons

**Comment by mcladyz** [comment] 2019-06-14 20:12
![Screenshot_20190614-230803](https://user-images.githubusercontent.com/6282039/59535524-de5abc00-8ef9-11e9-9449-dabbcaf5cd1a.png)
![Screenshot_20190614-231057](https://user-images.githubusercontent.com/6282039/59535530-e155ac80-8ef9-11e9-9930-9f3811e75483.png)

**Comment by tibbi** [comment] 2019-06-14 20:17
thats sick.. So if you click on a contact and open the View screen, the number is shown there? What is the type of the number? Home, Mobile, or something else? Do you have any spaces or special characters in the phone number?

**Comment by tibbi** [comment] 2019-06-14 20:28
seems like only the Menu -> Export contacts in an .vcf file is broken, sharing individual contacts isnt. Ill try fixing it soon. Thanks

**Comment by crbble** [comment] 2019-06-26 07:51
Can you reopen this so others can see it? I stumbled across the problem and it is extremely painful to realize that the Contact name and picture has been exported, but not the phone number [sic!].

**Comment by tibbi** [comment] 2019-06-26 08:08
well it should be fixed already. Retry with 6.3.2 please.

**Comment by crbble** [comment] 2019-06-26 09:11
Sorry, I am running 6.3.2 from fdroid and it is still exporting like shown in the Screenshot.
![Screenshot_20190626-110550_Markor png_resize jpg_resize](https://user-images.githubusercontent.com/5881641/60167263-0ce26c00-9803-11e9-85b6-85b6932d1b9e.jpg)

**Comment by tibbi** [comment] 2019-06-26 09:25
do you have any special characters at phone numbers? Can you try creating a new contact with Home phone number 123, then long pressing it at some list view, Share it, send yourself via email and check the file? Does it contain the phone number?

**Comment by crbble** [comment] 2019-06-26 10:06
Some (for example the first contact) numbers start with +49 and contain spaces, no other special characters. Sharing a single contact via messenger works and the phone number is shown. Sharing via email does not work, the vcf looks like the combined vcf. I am trying to get a logcat, but the app is not chatty.

**Comment by AIatMyCommand** [comment] 2019-07-06 02:42
Hi all. This is my first post/contribution to github so please bear with me.

I tried to export my contacts a few times & had mixed results (if I remember one time it didn't import the numbers but only the names & one time it worked) anyway I had to start over.

Anyway this latest attempt conacts exported properly with google website & import with simple contacts didn't import the numbers again. I solved the issue by using an alternative app: open contacts but this is only a temporary fix because I prefer simple contacts. Keep up the good work!

**Comment by SAL-e** [comment] 2019-07-07 07:18
I encounter same issue. Only exporting the names, but nothing else. This happened to me when I tried to export only online account and exclude the local db. If local db is selected during the export all data from online account is exported.

**Comment by tibbi** [comment] 2019-09-15 21:34
should be fixed in 6.4.0 released soon

**Closed by tibbi** 2019-09-15 21:34 UTC
Labels: bug
