### ISSUE TITLE
Take in consideration accented characters in sorting options

### ISSUE THREAD

**Issue by El-Gavy** [SimpleMobileTools/Simple-Contacts#160] opened 2018-05-04 21:29 UTC
When trying to sort the contacts list (on first name for instance) accented characters seem to be placed at the end of the alphabet. 

« é » should follow « e » but seems to be placed after « z »

Example of sorted list i get :

Celine
Coralie
Céline

**Comment by tibbi** [comment] 2018-05-04 21:36
duplicate of #131

**Closed by tibbi** 2018-05-04 21:36 UTC
