### ISSUE TITLE
No "IM" field!

### ISSUE THREAD

**Issue by Reue** [SimpleMobileTools/Simple-Contacts#198] opened 2018-07-11 21:35 UTC
Currently we are not limited to contacting people we know by phone or email.
In fact, today we contact many more people via their IM username ("Conversations", "Jabber", "Skype", "AIM", "Yahoo", "Hangouts", "ICQ", etc.) then via their phone or email.
So I think this application, like other contact programs, should have an "IM" (Instant messaging) field, where we could introduce the "IMs" that each of our contacts uses.
I suggest, at least, the following IMs and and additional "Custom" IM:
- Conversations
- Jabber
- Skype
- AIM
- Yahoo
- Hangouts
- ICQ
- IRC
Thanks in advance.

**Comment by tibbi** [comment] 2018-07-11 22:21
duplicate of #90

**Closed by tibbi** 2018-07-11 22:21 UTC
