### ISSUE TITLE
Members Count in Group Name Gets Confused 

### ISSUE THREAD

**Issue by bigboipete** [SimpleMobileTools/Simple-Contacts#589] opened 2020-08-03 06:47 UTC
Prerequisite: At least one contact in a group.

Reproduction:
1. Rename the group using an '&' like 'XXX & YYY'
-> Members count will increase of 1 or will be doubled (these are the variants, I experienced)
After this "confusion" any group renaming affects the counter.

Using Simple Contacts v6.12.6 Pro on a [Shift5me](https://shiftphones.com) with Shift OS (AOSP 8.0).

**Comment by tibbi** [comment] 2020-08-06 08:49
I cannot reproduce it. Are you sure it is caused by "&"?

**Comment by bigboipete** [comment] 2020-08-08 13:13
Yes, the "&" is the starting point on my device. But I'm not enough into Android to know how system things might interfere with app behaviour. My "special" setting (hardware and Android version as stated) might contribute to the issue, but I simply don't know for sure.

**Comment by bigboipete** [comment] 2020-12-03 11:32
I just rechecked this with my currently installed version 6.13.1 Pro. Faulty behavior is even more generic now: Even a simple group rename increases the memebers count. No '&' needs to be inolved anymore.

Unfortunately I can't tell, whether this more generic behavior was introduced along the way or was already there with 6.12.6 Pro.

@tibbi Is there any way to get e.g. some logs or something out of my device to support you fixing that?

**Comment by tibbi** [comment] 2020-12-03 18:17
not really, nothing like that helps

**Comment by bigboipete** [comment] 2021-06-02 14:08
Just for the record: Bug is still there in 6.15.0. It's the same behavior as described in my last post.

@tibbi If there is anything I could do to help debugging this, let me know.

**Comment by tibbi** [comment] 2021-11-18 08:14
should be fixed in 6.16.0

**Closed by tibbi** 2021-11-18 08:14 UTC
Labels: bug

**Comment by bigboipete** [comment] 2021-11-23 13:45
This works now on my Shift OS (AOSP 8.1). Thanks for the fix!!!
