### ISSUE TITLE
Alphabetical sort is all wrong!

### ISSUE THREAD

**Issue by Reue** [SimpleMobileTools/Simple-Contacts#194] opened 2018-07-11 20:49 UTC
This app can't sort contact names in alphabetical order, which means we have to use the finder or scroll all the list of contact names (which can be hundreds) to find a contact!
For example, the name "Ângela" appears on the bottom of the list, after names beguining with letter "Z"!
The name "João" appears after "José", etc.
This is a complete non sense. With the due respect I think this is weird and reveals very bad programming.
In about 25 years of using thousands of different types of programms (in Linux, Windows, Android) it is the first time I see something like this.
I hope this bug gets fixed soon.

**Comment by tibbi** [comment] 2018-07-11 21:01
duplicate of #131

**Closed by tibbi** 2018-07-11 21:01 UTC
